baseURL = 'https://the.lastgimbus.com/'
languageCode = 'en-us'
title = 'TheLastGimbus'

enableRobotsTXT = true

enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Enables use of <sub> and other html sutff in markdown
      unsafe = true
  [markup.highlight]
    noClasses=false