backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"

# For hugo ; TODO: Change folder path
# Duh, i want this dynamic :/
media_folder: "static/media" # Media files will be stored in the repo under static/images/uploads
public_folder: "/media" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{url}}"  # this means filename pretty much
    media_folder: "{{media_folder}}/../blog/{{url}}"
    public_folder: "/blog/{{url}}"
    fields:
      - label: "URL"
        name: "url"
        widget: "string"
        required: true
        pattern: ['^[a-zA-Z0-9_-]*$', 'Must be URL-Safe (no special chars etc)']
        comment: "URL and folder name for your post"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
